REPORTER(Parser)
REPORTER(AST)
REPORTER(Symbols)
REPORTER(InterfaceTypeID)
REPORTER(Concrete)
REPORTER(ConcreteID)
REPORTER(HyperGraph)
REPORTER(Automata)
REPORTER(ClangTraitsGen)
REPORTER(Decisions)
// REPORTER(ConcreteTypeID)
// REPORTER(Interface)
// REPORTER(Inheritance)
// REPORTER(AndOrTree)
// REPORTER(Enum)
// REPORTER(Derivation)
// REPORTER(BDD)
// REPORTER(TruthTable)
// REPORTER(Functions)
