REPORTER(Parser)
REPORTER(AST)
// REPORTER(Symbols)
// REPORTER(InterfaceTypeID)
// REPORTER(ConcreteTypeID)
// REPORTER(Interface)
// REPORTER(Inheritance)
// REPORTER(AndOrTree)
// REPORTER(Enum)
// REPORTER(Derivation)
// REPORTER(BDD)
// REPORTER(TruthTable)
// REPORTER(Functions)
