// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FORMAT_MEGA_H_
#define FLATBUFFERS_GENERATED_FORMAT_MEGA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

namespace Mega {

struct Vec3;

struct Test;
struct TestBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

struct Test FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POS = 4,
    VT_NAME = 6
  };
  const Mega::Vec3 *pos() const {
    return GetStruct<const Mega::Vec3 *>(VT_POS);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Mega::Vec3>(verifier, VT_POS, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct TestBuilder {
  typedef Test Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pos(const Mega::Vec3 *pos) {
    fbb_.AddStruct(Test::VT_POS, pos);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Test::VT_NAME, name);
  }
  explicit TestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Test> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Test>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Test> CreateTest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Mega::Vec3 *pos = nullptr,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  TestBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_pos(pos);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Test> CreateTestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Mega::Vec3 *pos = nullptr,
    const char *name = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return Mega::CreateTest(
      _fbb,
      pos,
      name__);
}

inline const Mega::Test *GetTest(const void *buf) {
  return ::flatbuffers::GetRoot<Mega::Test>(buf);
}

inline const Mega::Test *GetSizePrefixedTest(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Mega::Test>(buf);
}

inline bool VerifyTestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Mega::Test>(nullptr);
}

inline bool VerifySizePrefixedTestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Mega::Test>(nullptr);
}

inline void FinishTestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Mega::Test> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Mega::Test> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Mega

#endif  // FLATBUFFERS_GENERATED_FORMAT_MEGA_H_
