FILE_TYPE( FILE_InputParse_AST, STAGE_InputParse )
FILE_TYPE( FILE_InputParse_Body, STAGE_InputParse )
FILE_TYPE( FILE_Interface_Tree, STAGE_Interface )
FILE_TYPE( FILE_Analysis_ObjectCompile, STAGE_Analysis )
FILE_TYPE( FILE_Analysis_ObjectAnalysis, STAGE_Analysis )
