FILE_TYPE( FILE_InputParse_AST, STAGE_InputParse )
FILE_TYPE( FILE_InputParse_Body, STAGE_InputParse )
FILE_TYPE( FILE_InputParse_Extra, STAGE_InputParse )
FILE_TYPE( FILE_InterfaceStage_Tree, STAGE_InterfaceStage )
FILE_TYPE( FILE_Analysis_ObjectCompile, STAGE_Analysis )
FILE_TYPE( FILE_Analysis_ObjectAnalysis, STAGE_Analysis )
