Schematic(base;,0)
{
    Space(space_0001;,0)
    {
        transform(1,0,17,0,1,52.5)
        Contour(contour;,0)
        {
            path(-13,-53,65,-53,65,50,-13,50)
        }
        Property(width;,1)
        {
            value(0.5f;)
        }
        Space(spac_0003;,2)
        {
            transform(1,0,23,0,1,-72.5)
            Contour(contour;,0)
            {
                path(-30,108,-30,38,38,38,38,108)
            }
            Property(width;,1)
            {
                value(0.5f;)
            }
            Space(spac_0008;,2)
            {
                transform(-1,0,-16,0,1,40)
                Contour(contour;,0)
                {
                    path(-34,5,-20,5,-20,26,-34,26)
                }
                Property(width;,1)
                {
                    value(1;)
                }
                Cut(cut_0007;,2)
                {
                    transform(-1,0,-32,0,1,23)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Cut(cut__0008;,3)
                {
                    transform(-1,0,-32,0,1,18)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Pin(pin_0009;,4)
                {
                    position(-34,20)
                    Property(plane;,0)
                    {
                        value(Mid;)
                    }
                }
                Connection(conn_0007;,5)
                {
                    transform(2.66454e-15,-1,-34,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(2.5,3)
                    }
                }
            }
            Space(spac_0009;,3)
            {
                transform(1,0,58,0,1,82)
                Contour(contour;,0)
                {
                    path(-34,5,-20,5,-20,26,-34,26)
                }
                Property(width;,1)
                {
                    value(1;)
                }
                Cut(cut_0007;,2)
                {
                    transform(-1,0,-32,0,1,23)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Cut(cut__0008;,3)
                {
                    transform(-1,0,-32,0,1,18)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Pin(pin_0009;,4)
                {
                    position(-34,20)
                    Property(plane;,0)
                    {
                        value(Mid;)
                    }
                }
                Connection(conn_0007;,5)
                {
                    transform(2.66454e-15,-1,-34,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(2.5,3)
                    }
                }
            }
            Space(spac_0010;,4)
            {
                transform(1,0,58,0,1,40)
                Contour(contour;,0)
                {
                    path(-34,5,-20,5,-20,26,-34,26)
                }
                Property(width;,1)
                {
                    value(1;)
                }
                Cut(cut_0007;,2)
                {
                    transform(-1,0,-32,0,1,23)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Cut(cut__0008;,3)
                {
                    transform(-1,0,-32,0,1,18)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Pin(pin_0009;,4)
                {
                    position(-34,20)
                    Property(plane;,0)
                    {
                        value(Mid;)
                    }
                }
                Connection(conn_0007;,5)
                {
                    transform(2.66454e-15,-1,-34,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(2.5,3)
                    }
                }
            }
            Space(spac_0011;,5)
            {
                transform(1,0,58,0,1,61)
                Contour(contour;,0)
                {
                    path(-34,5,-20,5,-20,26,-34,26)
                }
                Property(width;,1)
                {
                    value(1;)
                }
                Cut(cut_0007;,2)
                {
                    transform(-1,0,-32,0,1,23)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Cut(cut__0008;,3)
                {
                    transform(-1,0,-32,0,1,18)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Pin(pin_0009;,4)
                {
                    position(-34,20)
                    Property(plane;,0)
                    {
                        value(Mid;)
                    }
                }
                Connection(conn_0007;,5)
                {
                    transform(2.66454e-15,-1,-34,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(2.5,3)
                    }
                }
            }
            Space(spac_0012;,6)
            {
                transform(-1,-0,-50,0,1,82)
                Contour(contour;,0)
                {
                    path(-34,5,-20,5,-20,26,-34,26)
                }
                Property(width;,1)
                {
                    value(1;)
                }
                Cut(cut_0007;,2)
                {
                    transform(-1,0,-32,0,1,23)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Cut(cut__0008;,3)
                {
                    transform(-1,0,-32,0,1,18)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Pin(pin_0009;,4)
                {
                    position(-34,20)
                    Property(plane;,0)
                    {
                        value(Mid;)
                    }
                }
                Connection(conn_0007;,5)
                {
                    transform(2.66454e-15,-1,-34,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(2.5,3)
                    }
                }
            }
            Space(spac_0013;,7)
            {
                transform(-1,-0,-50,0,1,61)
                Contour(contour;,0)
                {
                    path(-34,5,-20,5,-20,26,-34,26)
                }
                Property(width;,1)
                {
                    value(1;)
                }
                Cut(cut_0007;,2)
                {
                    transform(-1,0,-32,0,1,23)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Cut(cut__0008;,3)
                {
                    transform(-1,0,-32,0,1,18)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Pin(pin_0009;,4)
                {
                    position(-34,20)
                    Property(plane;,0)
                    {
                        value(Mid;)
                    }
                }
                Connection(conn_0007;,5)
                {
                    transform(2.66454e-15,-1,-34,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(2.5,3)
                    }
                }
            }
            Space(spac_0014;,8)
            {
                transform(-1,-0,-50,0,1,40)
                Contour(contour;,0)
                {
                    path(-34,5,-20,5,-20,26,-34,26)
                }
                Property(width;,1)
                {
                    value(1;)
                }
                Cut(cut_0007;,2)
                {
                    transform(-1,0,-32,0,1,23)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Cut(cut__0008;,3)
                {
                    transform(-1,0,-32,0,1,18)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Pin(pin_0009;,4)
                {
                    position(-34,20)
                    Property(plane;,0)
                    {
                        value(Mid;)
                    }
                }
                Connection(conn_0007;,5)
                {
                    transform(2.66454e-15,-1,-34,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(2.5,3)
                    }
                }
            }
            Space(spac_0016;,9)
            {
                transform(1,-0,24,-0,1,40)
                Contour(contour;,0)
                {
                    path(-34,5,-20,5,-20,26,-34,26)
                }
                Property(width;,1)
                {
                    value(1;)
                }
                Cut(cut_0007;,2)
                {
                    transform(-1,0,-32,0,1,23)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Cut(cut__0008;,3)
                {
                    transform(-1,0,-32,0,1,18)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Pin(pin_0009;,4)
                {
                    position(-34,20)
                    Property(plane;,0)
                    {
                        value(Mid;)
                    }
                }
                Connection(conn_0007;,5)
                {
                    transform(2.66454e-15,-1,-34,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(2.5,3)
                    }
                }
            }
            Space(spac_0017;,10)
            {
                transform(1,-0,24,-0,1,61)
                Contour(contour;,0)
                {
                    path(-34,47,-34,5,-6,5,-6,47)
                }
                Property(width;,1)
                {
                    value(1;)
                }
                Cut(cut_0007;,2)
                {
                    transform(-1,0,-32,0,1,23)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Cut(cut__0008;,3)
                {
                    transform(-1,0,-32,0,1,18)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Pin(pin_0009;,4)
                {
                    position(-34,20)
                    Property(plane;,0)
                    {
                        value(Mid;)
                    }
                }
                Connection(conn_0007;,5)
                {
                    transform(2.66454e-15,-1,-34,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(2.5,3)
                    }
                }
                Connection(conn_0006;,6)
                {
                    transform(2.66454e-15,-1,-20,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(2.5,3)
                    }
                }
                Connection(conn_0008;,7)
                {
                    transform(1,2.72005e-15,-27,2.72005e-15,-1,5)
                    Point(width;,0)
                    {
                        position(2.5,3)
                    }
                }
                Cut(cut__0009;,8)
                {
                    transform(-1,0,-32,-0,1,44)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Cut(cut__0010;,9)
                {
                    transform(-1,0,-32,-0,1,39)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Connection(conn_0010;,10)
                {
                    transform(2.66454e-15,-1,-34,-1,-2.66454e-15,33)
                    Point(width;,0)
                    {
                        position(2.5,3)
                    }
                }
                Cut(cut__0011;,11)
                {
                    transform(1,0,-8,0,1,44)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Cut(cut__0012;,12)
                {
                    transform(1,0,-8,0,1,39)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Connection(conn_0013;,13)
                {
                    transform(-2.66454e-15,1,-6,-1,-2.66454e-15,33)
                    Point(width;,0)
                    {
                        position(2.5,3)
                    }
                }
                Cut(cut__0014;,14)
                {
                    transform(1,0,-8,0,1,23)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Cut(cut__0015;,15)
                {
                    transform(1,0,-8,0,1,18)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Connection(conn_0016;,16)
                {
                    transform(-2.66454e-15,1,-6,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(2.5,3)
                    }
                }
                Connection(conn_0017;,17)
                {
                    transform(-1,-2.72005e-15,-13,2.72005e-15,-1,5)
                    Point(width;,0)
                    {
                        position(2.5,3)
                    }
                }
            }
            Connection(conn_0015;,11)
            {
                transform(1,0,4,0,1,38)
                Point(width;,0)
                {
                    position(5.5,1)
                }
            }
        }
    }
}
