Schematic(base;,0)
{
    Space(space_0000;,0)
    {
        transform(1,0,0,0,1,0)
        Contour(contour;,0)
        {
            path(0,0,128,0,128,128,0,128)
        }
        Property(width;,1)
        {
            value(0.25f;)
        }
        Space(space_0002;,2)
        {
            transform(1,0,44,0,1,52)
            Contour(contour;,0)
            {
                path(0,0,32,0,32,32,0,32)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(space_0002;,2)
            {
                transform(1,0,0,0,1,0)
                Contour(contour;,0)
                {
                    path(0,0,10,0,10,32,0,32)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(-2.66454e-15,1,10,-1,-2.66454e-15,16)
                    Point(width;,0)
                    {
                        position(1.5,3)
                    }
                }
                Cut(cut_0003;,3)
                {
                    transform(1,0,9,0,1,28)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(2,0)
                    }
                }
                Cut(cut__0004;,4)
                {
                    transform(1,0,9,0,1,20)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(2,0)
                    }
                }
                Pin(pin_0005;,5)
                {
                    position(10,24)
                    Property(plane;,0)
                    {
                        value(Mid;)
                    }
                }
                Connection(conn_0006;,6)
                {
                    transform(-2.66454e-15,1,0,-1,-2.66454e-15,24)
                    Point(width;,0)
                    {
                        position(2.5,3)
                    }
                }
                Property(lane_0007;,7)
                {
                    value(0.75f;)
                }
                Property(lane_0008;,8)
                {
                    value(0.15f;)
                }
                Property(pave_0009;,9)
                {
                    value(2.25f;)
                }
                Property(pave_0010;,10)
                {
                    value(0.15f;)
                }
                Property(clea_0011;,11)
                {
                    value(3.5f;)
                }
                Pin(pin__0012;,12)
                {
                    position(4,29)
                    Property(lanes;,0)
                    {
                        value(Gutter;)
                    }
                }
                Property(lane_0013;,13)
                {
                    value(0.75f;)
                }
                Property(lane_0014;,14)
                {
                    value(0.15f;)
                }
                Property(pave_0015;,15)
                {
                    value(2.25f;)
                }
                Property(pave_0016;,16)
                {
                    value(0.15f;)
                }
                Property(clea_0017;,17)
                {
                    value(3.5f;)
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,16,0,1,0)
                Contour(contour;,0)
                {
                    path(0,0,16,0,16,16,0,16)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(-2.66454e-15,1,0,-1,-2.66454e-15,8)
                    Point(width;,0)
                    {
                        position(1.5,3)
                    }
                }
                Cut(cut_0003;,3)
                {
                    transform(1,0,2,0,1,15)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(0,2)
                    }
                }
                Property(lane_0004;,4)
                {
                    value(0.75f;)
                }
                Property(lane_0005;,5)
                {
                    value(0.15f;)
                }
                Property(pave_0006;,6)
                {
                    value(2.25f;)
                }
                Property(pave_0007;,7)
                {
                    value(0.15f;)
                }
                Property(clea_0008;,8)
                {
                    value(3.5f;)
                }
                Cut(cut__0009;,9)
                {
                    transform(1,0,10,0,1,15)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(0,2)
                    }
                }
                Property(lane_0011;,10)
                {
                    value(0.75f;)
                }
                Property(lane_0012;,11)
                {
                    value(0.15f;)
                }
                Property(pave_0013;,12)
                {
                    value(2.25f;)
                }
                Property(pave_0014;,13)
                {
                    value(0.15f;)
                }
                Property(clea_0015;,14)
                {
                    value(3.5f;)
                }
                Pin(pin_0015;,15)
                {
                    position(6,16)
                    Property(plane;,0)
                    {
                        value(Hole;)
                    }
                }
                Property(lane_0016;,16)
                {
                    value(0.75f;)
                }
                Property(lane_0017;,17)
                {
                    value(0.15f;)
                }
                Property(pave_0018;,18)
                {
                    value(2.25f;)
                }
                Property(pave_0019;,19)
                {
                    value(0.15f;)
                }
                Property(clea_0020;,20)
                {
                    value(3.5f;)
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,16,0,1,16)
                Contour(contour;,0)
                {
                    path(0,0,16,0,16,16,0,16)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(-2.66454e-15,1,0,-1,-2.66454e-15,8)
                    Point(width;,0)
                    {
                        position(1.5,3)
                    }
                }
                Connection(conn_0003;,3)
                {
                    transform(1,0,12,0,1,0)
                    Point(width;,0)
                    {
                        position(1.5,3)
                    }
                }
            }
            Connection(conn_0005;,5)
            {
                transform(1,0,13,0,1,0)
                Point(width;,0)
                {
                    position(1.5,3)
                }
            }
            Connection(conn_0006;,6)
            {
                transform(1,0,13,0,1,32)
                Point(width;,0)
                {
                    position(1.5,3)
                }
            }
        }
    }
    Property(laneRadius;,1)
    {
        value(0.5;)
    }
    Property(laneLining;,2)
    {
        value(0.3;)
    }
    Property(pavementRadius;,3)
    {
        value(2.25f;)
    }
    Property(pavementLining;,4)
    {
        value(0.15f;)
    }
    Property(clearance;,5)
    {
        value(3.5;)
    }
}
