Schematic(base;,0)
{
    Space(space_0016;,0)
    {
        transform(1,0,112,0,1,112)
        Contour(contour;,0)
        {
            path(-112,-112,112,-112,112,112,-112,112)
        }
        Property(width;,1)
        {
            value(0.25f;)
        }
        Space(spac_0002;,2)
        {
            transform(1,-0,-42,-0,1,-86)
            Contour(contour;,0)
            {
                path(-14,-18,34,-18,34,30,-14,30)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(space_0002;,2)
            {
                transform(1,0,-6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,18,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0005;,5)
            {
                transform(1,6.66134e-16,18,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0006;,6)
            {
                transform(1,6.66134e-16,-6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0007;,7)
            {
                transform(1,6.66134e-16,6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
        }
        Space(spac_0003;,3)
        {
            transform(1,-0,-90,-0,1,-86)
            Contour(contour;,0)
            {
                path(-14,-18,34,-18,34,30,-14,30)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(space_0002;,2)
            {
                transform(1,0,-6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,18,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0005;,5)
            {
                transform(1,6.66134e-16,18,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0006;,6)
            {
                transform(1,6.66134e-16,-6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0007;,7)
            {
                transform(1,6.66134e-16,6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
        }
        Space(spac_0004;,4)
        {
            transform(1,-0,-90,-0,1,-38)
            Contour(contour;,0)
            {
                path(-14,-18,34,-18,34,30,-14,30)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(space_0002;,2)
            {
                transform(1,0,-6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,18,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0005;,5)
            {
                transform(1,6.66134e-16,18,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0006;,6)
            {
                transform(1,6.66134e-16,-6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0007;,7)
            {
                transform(1,6.66134e-16,6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
        }
        Space(spac_0008;,5)
        {
            transform(1,-0,-42,-0,1,-38)
            Contour(contour;,0)
            {
                path(-14,-18,34,-18,34,30,-14,30)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(space_0002;,2)
            {
                transform(1,0,-6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,18,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0005;,5)
            {
                transform(1,6.66134e-16,18,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0006;,6)
            {
                transform(1,6.66134e-16,-6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0007;,7)
            {
                transform(1,6.66134e-16,6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
        }
        Connection(conn_0018;,6)
        {
            transform(1,0,-80,0,1,-56)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0019;,7)
        {
            transform(1,0,-32,0,1,-56)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0020;,8)
        {
            transform(1,0,-80,0,1,-104)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0021;,9)
        {
            transform(-2.66454e-15,1,-56,-1,-2.66454e-15,-80)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0022;,10)
        {
            transform(-2.66454e-15,1,-8,-1,-2.66454e-15,-80)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0023;,11)
        {
            transform(-2.66454e-15,1,-56,-1,-2.66454e-15,-32)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0024;,12)
        {
            transform(-2.66454e-15,1,-8,-1,-2.66454e-15,-32)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0013;,13)
        {
            transform(1,0,32,0,1,-56)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0014;,14)
        {
            transform(1,0,32,0,1,-104)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0015;,15)
        {
            transform(-2.66454e-15,1,104,-1,-2.66454e-15,-80)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Space(spac_0016;,16)
        {
            transform(1,0,70,0,1,-86)
            Contour(contour;,0)
            {
                path(-14,-18,34,-18,34,30,-14,30)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(space_0002;,2)
            {
                transform(1,0,-6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,18,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0005;,5)
            {
                transform(1,6.66134e-16,18,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0006;,6)
            {
                transform(1,6.66134e-16,-6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0007;,7)
            {
                transform(1,6.66134e-16,6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
        }
        Connection(conn_0017;,17)
        {
            transform(-2.66454e-15,1,56,-1,-2.66454e-15,-32)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Space(spac_0018;,18)
        {
            transform(1,0,22,0,1,-38)
            Contour(contour;,0)
            {
                path(-14,-18,34,-18,34,30,-14,30)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(space_0002;,2)
            {
                transform(1,0,-6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,18,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0005;,5)
            {
                transform(1,6.66134e-16,18,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0006;,6)
            {
                transform(1,6.66134e-16,-6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0007;,7)
            {
                transform(1,6.66134e-16,6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
        }
        Space(spac_0019;,19)
        {
            transform(1,0,22,0,1,-86)
            Contour(contour;,0)
            {
                path(-14,-18,34,-18,34,30,-14,30)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(space_0002;,2)
            {
                transform(1,0,-6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,18,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0005;,5)
            {
                transform(1,6.66134e-16,18,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0006;,6)
            {
                transform(1,6.66134e-16,-6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0007;,7)
            {
                transform(1,6.66134e-16,6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
        }
        Space(spac_0020;,20)
        {
            transform(1,0,70,0,1,-38)
            Contour(contour;,0)
            {
                path(-14,-18,34,-18,34,30,-14,30)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(space_0002;,2)
            {
                transform(1,0,-6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,18,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0005;,5)
            {
                transform(1,6.66134e-16,18,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0006;,6)
            {
                transform(1,6.66134e-16,-6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0007;,7)
            {
                transform(1,6.66134e-16,6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
        }
        Connection(conn_0025;,21)
        {
            transform(1,0,80,0,1,-56)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0026;,22)
        {
            transform(-2.66454e-15,1,56,-1,-2.66454e-15,-80)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0027;,23)
        {
            transform(-2.66454e-15,1,104,-1,-2.66454e-15,-32)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0028;,24)
        {
            transform(-2.66454e-15,1,56,-1,-2.66454e-15,80)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0029;,25)
        {
            transform(1,0,32,0,1,8)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Space(spac_0026;,26)
        {
            transform(1,0,70,0,1,26)
            Contour(contour;,0)
            {
                path(-14,-18,34,-18,34,30,-14,30)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(space_0002;,2)
            {
                transform(1,0,-6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,18,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0005;,5)
            {
                transform(1,6.66134e-16,18,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0006;,6)
            {
                transform(1,6.66134e-16,-6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0007;,7)
            {
                transform(1,6.66134e-16,6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
        }
        Space(spac_0027;,27)
        {
            transform(1,0,22,0,1,74)
            Contour(contour;,0)
            {
                path(-14,-18,34,-18,34,30,-14,30)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(space_0002;,2)
            {
                transform(1,0,-6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,18,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0005;,5)
            {
                transform(1,6.66134e-16,18,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0006;,6)
            {
                transform(1,6.66134e-16,-6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0007;,7)
            {
                transform(1,6.66134e-16,6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
        }
        Connection(conn_0030;,28)
        {
            transform(-2.66454e-15,1,104,-1,-2.66454e-15,80)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0031;,29)
        {
            transform(-2.66454e-15,1,56,-1,-2.66454e-15,32)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0032;,30)
        {
            transform(1,0,80,0,1,56)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Space(spac_0031;,31)
        {
            transform(1,0,70,0,1,74)
            Contour(contour;,0)
            {
                path(-14,-18,34,-18,34,30,-14,30)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(space_0002;,2)
            {
                transform(1,0,-6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,18,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0005;,5)
            {
                transform(1,6.66134e-16,18,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0006;,6)
            {
                transform(1,6.66134e-16,-6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0007;,7)
            {
                transform(1,6.66134e-16,6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
        }
        Space(spac_0032;,32)
        {
            transform(1,0,22,0,1,26)
            Contour(contour;,0)
            {
                path(-14,-18,34,-18,34,30,-14,30)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(space_0002;,2)
            {
                transform(1,0,-6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,18,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0005;,5)
            {
                transform(1,6.66134e-16,18,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0006;,6)
            {
                transform(1,6.66134e-16,-6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0007;,7)
            {
                transform(1,6.66134e-16,6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
        }
        Connection(conn_0033;,33)
        {
            transform(1,0,32,0,1,56)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0034;,34)
        {
            transform(-2.66454e-15,1,104,-1,-2.66454e-15,32)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Space(spac_0035;,35)
        {
            transform(1,0,-42,0,1,74)
            Contour(contour;,0)
            {
                path(-14,-18,34,-18,34,30,-14,30)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(space_0002;,2)
            {
                transform(1,0,-6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,18,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0005;,5)
            {
                transform(1,6.66134e-16,18,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0006;,6)
            {
                transform(1,6.66134e-16,-6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0007;,7)
            {
                transform(1,6.66134e-16,6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
        }
        Connection(conn_0036;,36)
        {
            transform(-2.66454e-15,1,-8,-1,-2.66454e-15,80)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Space(spac_0037;,37)
        {
            transform(1,0,-90,0,1,74)
            Contour(contour;,0)
            {
                path(-14,-18,34,-18,34,30,-14,30)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(space_0002;,2)
            {
                transform(1,0,-6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,18,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0005;,5)
            {
                transform(1,6.66134e-16,18,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0006;,6)
            {
                transform(1,6.66134e-16,-6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0007;,7)
            {
                transform(1,6.66134e-16,6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
        }
        Connection(conn_0038;,38)
        {
            transform(1,0,-80,0,1,56)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0039;,39)
        {
            transform(-2.66454e-15,1,-8,-1,-2.66454e-15,32)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0040;,40)
        {
            transform(-2.66454e-15,1,-56,-1,-2.66454e-15,80)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Space(spac_0041;,41)
        {
            transform(1,0,-42,0,1,26)
            Contour(contour;,0)
            {
                path(-14,-18,34,-18,34,30,-14,30)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(space_0002;,2)
            {
                transform(1,0,-6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,18,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0005;,5)
            {
                transform(1,6.66134e-16,18,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0006;,6)
            {
                transform(1,6.66134e-16,-6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0007;,7)
            {
                transform(1,6.66134e-16,6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
        }
        Connection(conn_0042;,42)
        {
            transform(1,0,-80,0,1,8)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Space(spac_0043;,43)
        {
            transform(1,0,-90,0,1,26)
            Contour(contour;,0)
            {
                path(-14,-18,34,-18,34,30,-14,30)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(space_0002;,2)
            {
                transform(1,0,-6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,6,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,18,0,1,-24)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0005;,5)
            {
                transform(1,6.66134e-16,18,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0006;,6)
            {
                transform(1,6.66134e-16,-6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
            Space(spac_0007;,7)
            {
                transform(1,6.66134e-16,6,6.66134e-16,-1,36)
                Contour(contour;,0)
                {
                    path(-2,12,10,12,10,24,-2,24)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,4,0,1,24)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
        }
        Connection(conn_0044;,44)
        {
            transform(-2.66454e-15,1,-56,-1,-2.66454e-15,32)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
        Connection(conn_0045;,45)
        {
            transform(1,0,-32,0,1,56)
            Point(width;,0)
            {
                position(1.5,3)
            }
        }
    }
}
