Schematic(base;,0)
{
    Space(space_0000;,0)
    {
        transform(1,0,0,0,1,0)
        Contour(contour;,0)
        {
            path(384,0,384,384,0,384,0,0)
        }
        Property(width;,1)
        {
            value(0.5f;)
        }
        Space(spac_0007;,2)
        {
            transform(1,0,144,0,1,152)
            Contour(contour;,0)
            {
                path(96,24,96,96,0,96,0,24)
            }
            Property(width;,1)
            {
                value(0.5f;)
            }
            Space(spac_0002;,2)
            {
                transform(1,0,16,0,1,80)
                Contour(contour;,0)
                {
                    path(-16,16,-16,-16,48,-16,48,16)
                }
                Property(width;,1)
                {
                    value(0.5f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(-2.66454e-15,1,48,-1,-2.66454e-15,0)
                    Point(width;,0)
                    {
                        position(5.5,2)
                    }
                }
                Connection(conn_0003;,3)
                {
                    transform(1,0,16,0,1,-16)
                    Point(width;,0)
                    {
                        position(7.5,1)
                    }
                }
                Connection(conn_0004;,4)
                {
                    transform(1,0,0,0,1,-24)
                    Point(width;,0)
                    {
                        position(3.5,1)
                    }
                }
                Connection(conn_0005;,5)
                {
                    transform(1,0,48,0,1,-24)
                    Point(width;,0)
                    {
                        position(7.5,1)
                    }
                }
                Wall(wall_0006;,6)
                {
                    transform(1,0,-8,0,1,8)
                    Contour(contour;,0)
                    {
                        path(0,-4,4,-8,4,-12,8,-12,16,-8,16,-4,8,0,0,0)
                    }
                    Property(width;,1)
                    {
                        value(;)
                    }
                }
                Wall(wall_0007;,7)
                {
                    transform(-1,0,40,0,1,4)
                    Contour(contour;,0)
                    {
                        path(0,-4,4,-8,4,-12,8,-12,16,-8,16,-4,8,0,0,0)
                    }
                    Property(width;,1)
                    {
                        value(;)
                    }
                }
            }
            Space(spac_0004;,3)
            {
                transform(1,0,80,0,1,80)
                Contour(contour;,0)
                {
                    path(-16,-16,16,-16,16,16,-16,16)
                }
                Property(width;,1)
                {
                    value(0.5f;)
                }
                Wall(wall_0002;,2)
                {
                    transform(1,0,-11,0,1,12)
                    Contour(contour;,0)
                    {
                        path(0,0,0,-8,8,-8,8,0)
                    }
                    Property(width;,1)
                    {
                        value(;)
                    }
                }
                Wall(wall_0003;,3)
                {
                    transform(1,0,8,0,1,9)
                    Contour(contour;,0)
                    {
                        path(0,0,0,-8,8,-8,8,0)
                    }
                    Property(width;,1)
                    {
                        value(;)
                    }
                }
                Wall(wall_0004;,4)
                {
                    transform(1,0,-9,0,1,-8)
                    Contour(contour;,0)
                    {
                        path(0,0,0,-8,8,-8,8,0)
                    }
                    Property(width;,1)
                    {
                        value(;)
                    }
                }
            }
            Space(spac_0005;,4)
            {
                transform(1,0,16,0,1,40)
                Contour(contour;,0)
                {
                    path(-16,-16,16,-16,16,16,-16,16)
                }
                Property(width;,1)
                {
                    value(0.5f;)
                }
            }
            Space(spac_0006;,5)
            {
                transform(1,0,48,0,1,40)
                Contour(contour;,0)
                {
                    path(-16,16,-16,-16,48,-16,48,16)
                }
                Property(width;,1)
                {
                    value(0.5f;)
                }
                Wall(wall_0002;,2)
                {
                    transform(1,0,-8,0,1,8)
                    Contour(contour;,0)
                    {
                        path(0,-4,4,-8,4,-12,8,-12,16,-8,16,-4,8,0,0,0)
                    }
                    Property(width;,1)
                    {
                        value(;)
                    }
                }
                Wall(wall_0003;,3)
                {
                    transform(-1,0,40,0,1,4)
                    Contour(contour;,0)
                    {
                        path(0,-4,4,-8,4,-12,8,-12,16,-8,16,-4,8,0,0,0)
                    }
                    Property(width;,1)
                    {
                        value(;)
                    }
                }
                Cut(cut_0004;,4)
                {
                    transform(1,0,24,0,1,-8)
                    LineSegment(segment;,0)
                    {
                        start(1,-3)
                        end(1,14)
                    }
                }
                Cut(cut__0005;,5)
                {
                    transform(1,0,25,0,1,-8)
                    LineSegment(segment;,0)
                    {
                        start(1,-3)
                        end(1,14)
                    }
                }
                Cut(cut__0006;,6)
                {
                    transform(1,0,26,0,1,-8)
                    LineSegment(segment;,0)
                    {
                        start(1,-3)
                        end(1,14)
                    }
                }
                Cut(cut__0007;,7)
                {
                    transform(1,0,27,0,1,-8)
                    LineSegment(segment;,0)
                    {
                        start(1,-3)
                        end(1,14)
                    }
                }
                Cut(cut__0008;,8)
                {
                    transform(1,0,29,0,1,-8)
                    LineSegment(segment;,0)
                    {
                        start(1,-3)
                        end(1,14)
                    }
                }
                Cut(cut__0009;,9)
                {
                    transform(1,0,28,0,1,-8)
                    LineSegment(segment;,0)
                    {
                        start(1,-3)
                        end(1,14)
                    }
                }
            }
            Connection(conn_0006;,6)
            {
                transform(-2.66454e-15,1,96,-1,-2.66454e-15,60)
                Point(width;,0)
                {
                    position(3.5,1)
                }
            }
            Connection(conn_0007;,7)
            {
                transform(-2.66454e-15,1,0,-1,-2.66454e-15,60)
                Point(width;,0)
                {
                    position(3.5,1)
                }
            }
        }
    }
}
