Schematic(base;,0)
{
    Space(space_0000;,0)
    {
        transform(1,0,0,0,1,0)
        Contour(contour;,0)
        {
            path(0,0,320,0,320,320,0,320)
        }
        Property(width;,1)
        {
            value(0.5f;)
        }
        Space(spac_0004;,2)
        {
            transform(-1,0,34,0,-1,58)
            Contour(contour;,0)
            {
                path(-34,-16,16,-16,16,40,-34,40)
            }
            Property(width;,1)
            {
                value(2;)
            }
            Connection(conn_0002;,2)
            {
                transform(2.66454e-15,-1,-34,-1,-2.66454e-15,30)
                Point(width;,0)
                {
                    position(4.5,6)
                }
            }
            Space(space_0003;,3)
            {
                transform(-1,0,-9,0,1,15)
                Contour(contour;,0)
                {
                    path(0,0,24,0,24,24,0,24)
                }
                Property(width;,1)
                {
                    value(0.5;)
                }
                Connection(conn_0002;,2)
                {
                    transform(-2.66454e-15,1,3,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(5.5,10)
                    }
                }
                Wall(wall_0003;,3)
                {
                    transform(1,0,2,0,1,12)
                    Contour(contour;,0)
                    {
                        path(-2,6,-2,-6,4,-6,4,6)
                    }
                    Property(width;,1)
                    {
                        value(1;)
                    }
                }
            }
            Connection(conn_0004;,4)
            {
                transform(-2.66454e-15,1,16,-1,-2.66454e-15,-4)
                Point(width;,0)
                {
                    position(5.5,3)
                }
            }
            Connection(conn_0005;,5)
            {
                transform(-1,-5.21805e-15,2,5.21805e-15,-1,-16)
                Point(width;,0)
                {
                    position(5.5,3)
                }
            }
        }
        Space(spac_0003;,3)
        {
            transform(1,0,102,0,1,34)
            Contour(contour;,0)
            {
                path(-34,-16,16,-16,16,40,-34,40)
            }
            Property(width;,1)
            {
                value(2;)
            }
            Connection(conn_0002;,2)
            {
                transform(2.66454e-15,-1,-34,-1,-2.66454e-15,30)
                Point(width;,0)
                {
                    position(4.5,6)
                }
            }
            Space(space_0003;,3)
            {
                transform(-1,0,-9,0,1,15)
                Contour(contour;,0)
                {
                    path(0,0,24,0,24,24,0,24)
                }
                Property(width;,1)
                {
                    value(0.5;)
                }
                Connection(conn_0002;,2)
                {
                    transform(-2.66454e-15,1,3,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(5.5,10)
                    }
                }
                Wall(wall_0003;,3)
                {
                    transform(1,0,2,0,1,12)
                    Contour(contour;,0)
                    {
                        path(-2,6,-2,-6,4,-6,4,6)
                    }
                    Property(width;,1)
                    {
                        value(1;)
                    }
                }
            }
            Connection(conn_0004;,4)
            {
                transform(-2.66454e-15,1,16,-1,-2.66454e-15,-4)
                Point(width;,0)
                {
                    position(5.5,3)
                }
            }
            Pin(pin__0005;,5)
            {
                position(-20,2)
                Property(room;,0)
                {
                    value(Corridor;)
                }
            }
        }
        Space(spac_0005;,4)
        {
            transform(1,0,52,0,1,90)
            Contour(contour;,0)
            {
                path(-34,-16,16,-16,16,40,-34,40)
            }
            Property(width;,1)
            {
                value(2;)
            }
            Connection(conn_0002;,2)
            {
                transform(2.66454e-15,-1,-34,-1,-2.66454e-15,30)
                Point(width;,0)
                {
                    position(4.5,6)
                }
            }
            Space(space_0003;,3)
            {
                transform(-1,0,-9,0,1,15)
                Contour(contour;,0)
                {
                    path(0,0,24,0,24,24,0,24)
                }
                Property(width;,1)
                {
                    value(0.5;)
                }
                Connection(conn_0002;,2)
                {
                    transform(-2.66454e-15,1,3,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(5.5,10)
                    }
                }
                Wall(wall_0003;,3)
                {
                    transform(1,0,2,0,1,12)
                    Contour(contour;,0)
                    {
                        path(-2,6,-2,-6,4,-6,4,6)
                    }
                    Property(width;,1)
                    {
                        value(1;)
                    }
                }
            }
            Connection(conn_0004;,4)
            {
                transform(-2.66454e-15,1,16,-1,-2.66454e-15,-4)
                Point(width;,0)
                {
                    position(5.5,3)
                }
            }
            Pin(pin__0005;,5)
            {
                position(-20,2)
                Property(room;,0)
                {
                    value(Corridor;)
                }
            }
        }
        Space(spac_0006;,5)
        {
            transform(-1,0,84,0,-1,114)
            Contour(contour;,0)
            {
                path(16,40,-34,40,-34,-72,16,-72)
            }
            Property(width;,1)
            {
                value(2;)
            }
            Connection(conn_0002;,2)
            {
                transform(2.66454e-15,-1,-34,-1,-2.66454e-15,30)
                Point(width;,0)
                {
                    position(4.5,6)
                }
            }
            Space(space_0003;,3)
            {
                transform(-1,0,-9,0,1,15)
                Contour(contour;,0)
                {
                    path(0,0,24,0,24,24,0,24)
                }
                Property(width;,1)
                {
                    value(0.5;)
                }
                Connection(conn_0002;,2)
                {
                    transform(-2.66454e-15,1,3,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(5.5,10)
                    }
                }
                Wall(wall_0003;,3)
                {
                    transform(1,0,2,0,1,12)
                    Contour(contour;,0)
                    {
                        path(-2,6,-2,-6,4,-6,4,6)
                    }
                    Property(width;,1)
                    {
                        value(1;)
                    }
                }
            }
            Connection(conn_0004;,4)
            {
                transform(-2.66454e-15,1,16,-1,-2.66454e-15,-4)
                Point(width;,0)
                {
                    position(5.5,3)
                }
            }
            Connection(conn_0005;,5)
            {
                transform(-2.66454e-15,1,16,1,2.66454e-15,-62)
                Point(width;,0)
                {
                    position(4.5,6)
                }
            }
            Space(spac_0006;,6)
            {
                transform(1,-0,-9,-0,-1,-47)
                Contour(contour;,0)
                {
                    path(0,0,24,0,24,24,0,24)
                }
                Property(width;,1)
                {
                    value(0.5;)
                }
                Connection(conn_0002;,2)
                {
                    transform(-2.66454e-15,1,3,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(5.5,10)
                    }
                }
                Wall(wall_0003;,3)
                {
                    transform(1,0,2,0,1,12)
                    Contour(contour;,0)
                    {
                        path(-2,6,-2,-6,4,-6,4,6)
                    }
                    Property(width;,1)
                    {
                        value(1;)
                    }
                }
            }
            Pin(pin__0007;,7)
            {
                position(4,-38)
                Property(lanes;,0)
                {
                    value(Gutter;)
                }
            }
            Pin(pin__0008;,8)
            {
                position(-4,-38)
                Property(lanes;,0)
                {
                    value(Pavement;)
                }
            }
        }
        Space(spac_0016;,6)
        {
            transform(-1,0,84,0,-1,226)
            Contour(contour;,0)
            {
                path(-34,-16,16,-16,16,40,-34,40)
            }
            Property(width;,1)
            {
                value(2;)
            }
            Connection(conn_0002;,2)
            {
                transform(2.66454e-15,-1,-34,-1,-2.66454e-15,30)
                Point(width;,0)
                {
                    position(4.5,6)
                }
            }
            Space(space_0003;,3)
            {
                transform(-1,0,-9,0,1,15)
                Contour(contour;,0)
                {
                    path(0,0,24,0,24,24,0,24)
                }
                Property(width;,1)
                {
                    value(0.5;)
                }
                Connection(conn_0002;,2)
                {
                    transform(-2.66454e-15,1,3,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(5.5,10)
                    }
                }
                Wall(wall_0003;,3)
                {
                    transform(1,0,2,0,1,12)
                    Contour(contour;,0)
                    {
                        path(-2,6,-2,-6,4,-6,4,6)
                    }
                    Property(width;,1)
                    {
                        value(1;)
                    }
                }
            }
            Connection(conn_0004;,4)
            {
                transform(-2.66454e-15,1,16,-1,-2.66454e-15,-4)
                Point(width;,0)
                {
                    position(5.5,3)
                }
            }
        }
        Space(spac_0017;,7)
        {
            transform(1,0,52,0,1,202)
            Contour(contour;,0)
            {
                path(-34,-16,16,-16,16,40,-34,40)
            }
            Property(width;,1)
            {
                value(2;)
            }
            Connection(conn_0002;,2)
            {
                transform(2.66454e-15,-1,-34,-1,-2.66454e-15,30)
                Point(width;,0)
                {
                    position(4.5,6)
                }
            }
            Space(space_0003;,3)
            {
                transform(-1,0,-9,0,1,15)
                Contour(contour;,0)
                {
                    path(0,0,24,0,24,24,0,24)
                }
                Property(width;,1)
                {
                    value(0.5;)
                }
                Connection(conn_0002;,2)
                {
                    transform(-2.66454e-15,1,3,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(5.5,10)
                    }
                }
                Wall(wall_0003;,3)
                {
                    transform(1,0,2,0,1,12)
                    Contour(contour;,0)
                    {
                        path(-2,6,-2,-6,4,-6,4,6)
                    }
                    Property(width;,1)
                    {
                        value(1;)
                    }
                }
            }
            Connection(conn_0004;,4)
            {
                transform(-2.66454e-15,1,16,-1,-2.66454e-15,-4)
                Point(width;,0)
                {
                    position(5.5,3)
                }
            }
            Pin(pin__0005;,5)
            {
                position(-20,2)
                Property(room;,0)
                {
                    value(Corridor;)
                }
            }
        }
        Space(spac_0018;,8)
        {
            transform(-1,0,34,0,-1,170)
            Contour(contour;,0)
            {
                path(-34,-16,16,-16,16,40,-34,40)
            }
            Property(width;,1)
            {
                value(2;)
            }
            Connection(conn_0002;,2)
            {
                transform(2.66454e-15,-1,-34,-1,-2.66454e-15,30)
                Point(width;,0)
                {
                    position(4.5,6)
                }
            }
            Space(space_0003;,3)
            {
                transform(-1,0,-9,0,1,15)
                Contour(contour;,0)
                {
                    path(0,0,24,0,24,24,0,24)
                }
                Property(width;,1)
                {
                    value(0.5;)
                }
                Connection(conn_0002;,2)
                {
                    transform(-2.66454e-15,1,3,-1,-2.66454e-15,12)
                    Point(width;,0)
                    {
                        position(5.5,10)
                    }
                }
                Wall(wall_0003;,3)
                {
                    transform(1,0,2,0,1,12)
                    Contour(contour;,0)
                    {
                        path(-2,6,-2,-6,4,-6,4,6)
                    }
                    Property(width;,1)
                    {
                        value(1;)
                    }
                }
            }
            Connection(conn_0004;,4)
            {
                transform(-2.66454e-15,1,16,-1,-2.66454e-15,-4)
                Point(width;,0)
                {
                    position(5.5,3)
                }
            }
            Connection(conn_0005;,5)
            {
                transform(-1,-5.21805e-15,2,5.21805e-15,-1,-16)
                Point(width;,0)
                {
                    position(5.5,3)
                }
            }
        }
        Space(space_0015;,9)
        {
            transform(1,0,200,0,1,134)
            Contour(contour;,0)
            {
                path(-50,-112,50,-112,50,112,-50,112,-50,82,-66,70,-66,50,-82,34,-82,-38,-64,-38,-64,-76,-50,-86)
            }
            Property(width;,1)
            {
                value(2;)
            }
            Space(spac_0002;,2)
            {
                transform(-1,-0,16,-0,-1,-16)
                Contour(contour;,0)
                {
                    path(-34,-16,16,-16,16,40,-34,40)
                }
                Property(width;,1)
                {
                    value(2;)
                }
                Connection(conn_0002;,2)
                {
                    transform(2.66454e-15,-1,-34,-1,-2.66454e-15,30)
                    Point(width;,0)
                    {
                        position(4.5,6)
                    }
                }
                Space(space_0003;,3)
                {
                    transform(-1,0,-9,0,1,15)
                    Contour(contour;,0)
                    {
                        path(0,0,24,0,24,24,0,24)
                    }
                    Property(width;,1)
                    {
                        value(0.5;)
                    }
                    Connection(conn_0002;,2)
                    {
                        transform(-2.66454e-15,1,3,-1,-2.66454e-15,12)
                        Point(width;,0)
                        {
                            position(5.5,10)
                        }
                    }
                    Wall(wall_0003;,3)
                    {
                        transform(1,0,2,0,1,12)
                        Contour(contour;,0)
                        {
                            path(-2,6,-2,-6,4,-6,4,6)
                        }
                        Property(width;,1)
                        {
                            value(1;)
                        }
                    }
                }
                Connection(conn_0004;,4)
                {
                    transform(-2.66454e-15,1,16,-1,-2.66454e-15,-4)
                    Point(width;,0)
                    {
                        position(5.5,3)
                    }
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,-16,0,1,-40)
                Contour(contour;,0)
                {
                    path(-34,-16,16,-16,16,40,-34,40)
                }
                Property(width;,1)
                {
                    value(2;)
                }
                Connection(conn_0002;,2)
                {
                    transform(2.66454e-15,-1,-34,-1,-2.66454e-15,30)
                    Point(width;,0)
                    {
                        position(4.5,6)
                    }
                }
                Space(space_0003;,3)
                {
                    transform(-1,0,-9,0,1,15)
                    Contour(contour;,0)
                    {
                        path(0,0,24,0,24,24,0,24)
                    }
                    Property(width;,1)
                    {
                        value(0.5;)
                    }
                    Connection(conn_0002;,2)
                    {
                        transform(-2.66454e-15,1,3,-1,-2.66454e-15,12)
                        Point(width;,0)
                        {
                            position(5.5,10)
                        }
                    }
                    Wall(wall_0003;,3)
                    {
                        transform(1,0,2,0,1,12)
                        Contour(contour;,0)
                        {
                            path(-2,6,-2,-6,4,-6,4,6)
                        }
                        Property(width;,1)
                        {
                            value(1;)
                        }
                    }
                }
                Connection(conn_0004;,4)
                {
                    transform(-2.66454e-15,1,16,-1,-2.66454e-15,-4)
                    Point(width;,0)
                    {
                        position(5.5,3)
                    }
                }
                Pin(pin__0005;,5)
                {
                    position(-20,2)
                    Property(room;,0)
                    {
                        value(Corridor;)
                    }
                }
                Pin(pin__0006;,6)
                {
                    position(-12,2)
                    Property(lanes;,0)
                    {
                        value(Gutter;)
                    }
                }
                Pin(pin__0007;,7)
                {
                    position(-4,2)
                    Property(lanes;,0)
                    {
                        value(Gutter;)
                    }
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,-16,0,1,72)
                Contour(contour;,0)
                {
                    path(-34,-72,16,-72,16,40,-34,40)
                }
                Property(width;,1)
                {
                    value(2;)
                }
                Connection(conn_0002;,2)
                {
                    transform(2.66454e-15,-1,-34,-1,-2.66454e-15,30)
                    Point(width;,0)
                    {
                        position(4.5,6)
                    }
                }
                Space(space_0003;,3)
                {
                    transform(-1,0,-9,0,1,15)
                    Contour(contour;,0)
                    {
                        path(0,0,24,0,24,24,0,24)
                    }
                    Property(width;,1)
                    {
                        value(0.5;)
                    }
                    Connection(conn_0002;,2)
                    {
                        transform(-2.66454e-15,1,3,-1,-2.66454e-15,12)
                        Point(width;,0)
                        {
                            position(5.5,10)
                        }
                    }
                    Wall(wall_0003;,3)
                    {
                        transform(1,0,2,0,1,12)
                        Contour(contour;,0)
                        {
                            path(-2,6,-2,-6,4,-6,4,6)
                        }
                        Property(width;,1)
                        {
                            value(1;)
                        }
                    }
                }
                Connection(conn_0004;,4)
                {
                    transform(-2.66454e-15,1,16,-1,-2.66454e-15,-4)
                    Point(width;,0)
                    {
                        position(5.5,3)
                    }
                }
                Pin(pin__0005;,5)
                {
                    position(-20,2)
                    Property(room;,0)
                    {
                        value(Corridor;)
                    }
                }
                Connection(conn_0006;,6)
                {
                    transform(-2.66454e-15,1,16,1,2.66454e-15,-62)
                    Point(width;,0)
                    {
                        position(4.5,6)
                    }
                }
                Space(spac_0007;,7)
                {
                    transform(1,0,-9,-0,-1,-47)
                    Contour(contour;,0)
                    {
                        path(0,0,24,0,24,24,0,24)
                    }
                    Property(width;,1)
                    {
                        value(0.5;)
                    }
                    Connection(conn_0002;,2)
                    {
                        transform(-2.66454e-15,1,3,-1,-2.66454e-15,12)
                        Point(width;,0)
                        {
                            position(5.5,10)
                        }
                    }
                    Wall(wall_0003;,3)
                    {
                        transform(1,0,2,0,1,12)
                        Contour(contour;,0)
                        {
                            path(-2,6,-2,-6,4,-6,4,6)
                        }
                        Property(width;,1)
                        {
                            value(1;)
                        }
                    }
                }
                Connection(conn_0008;,8)
                {
                    transform(2.66454e-15,-1,-34,1,2.66454e-15,-28)
                    Point(width;,0)
                    {
                        position(5.5,3)
                    }
                }
            }
            Space(spac_0005;,5)
            {
                transform(1,0,34,0,1,-96)
                Contour(contour;,0)
                {
                    path(-84,40,-84,-16,16,-16,16,40)
                }
                Property(width;,1)
                {
                    value(2;)
                }
                Connection(conn_0004;,2)
                {
                    transform(-2.66454e-15,1,16,-1,-2.66454e-15,-4)
                    Point(width;,0)
                    {
                        position(5.5,3)
                    }
                }
                Connection(conn_0008;,3)
                {
                    transform(2.66454e-15,-1,-84,1,2.66454e-15,28)
                    Point(width;,0)
                    {
                        position(5.5,3)
                    }
                }
                Connection(conn_0009;,4)
                {
                    transform(1,5.21805e-15,-60,-5.21805e-15,1,40)
                    Point(width;,0)
                    {
                        position(13.5,3)
                    }
                }
                Pin(pin__0005;,5)
                {
                    position(-58,18)
                    Property(lanes;,0)
                    {
                        value(Gutter;)
                    }
                }
                Pin(pin__0006;,6)
                {
                    position(-50,18)
                    Property(lanes;,0)
                    {
                        value(Pavement;)
                    }
                }
            }
            Space(spac_0006;,6)
            {
                transform(1,0,34,0,1,16)
                Contour(contour;,0)
                {
                    path(-34,-16,16,-16,16,40,-34,40)
                }
                Property(width;,1)
                {
                    value(2;)
                }
                Connection(conn_0002;,2)
                {
                    transform(2.66454e-15,-1,-34,-1,-2.66454e-15,30)
                    Point(width;,0)
                    {
                        position(4.5,6)
                    }
                }
                Space(space_0003;,3)
                {
                    transform(-1,0,-9,0,1,15)
                    Contour(contour;,0)
                    {
                        path(0,0,13,-9,24,-9,24,24,0,24)
                    }
                    Property(width;,1)
                    {
                        value(0.5;)
                    }
                    Connection(conn_0002;,2)
                    {
                        transform(-2.66454e-15,1,0,-1,-2.66454e-15,14)
                        Point(width;,0)
                        {
                            position(5.5,10)
                        }
                    }
                }
                Connection(conn_0004;,4)
                {
                    transform(-2.66454e-15,1,16,-1,-2.66454e-15,-4)
                    Point(width;,0)
                    {
                        position(5.5,3)
                    }
                }
                Pin(pin__0005;,5)
                {
                    position(-20,2)
                    Property(room;,0)
                    {
                        value(Corridor;)
                    }
                }
                Pin(pin__0006;,6)
                {
                    position(-10,2)
                    Property(lanes;,0)
                    {
                        value(Pavement;)
                    }
                }
            }
            Space(spac_0007;,7)
            {
                transform(-1,-0,16,-0,-1,96)
                Contour(contour;,0)
                {
                    path(-34,-16,16,-16,16,40,-34,40)
                }
                Property(width;,1)
                {
                    value(2;)
                }
                Connection(conn_0002;,2)
                {
                    transform(2.66454e-15,-1,-34,-1,-2.66454e-15,30)
                    Point(width;,0)
                    {
                        position(4.5,6)
                    }
                }
                Space(space_0003;,3)
                {
                    transform(-1,0,-9,0,1,15)
                    Contour(contour;,0)
                    {
                        path(0,0,24,0,24,24,0,24)
                    }
                    Property(width;,1)
                    {
                        value(0.5;)
                    }
                    Connection(conn_0002;,2)
                    {
                        transform(-2.66454e-15,1,3,-1,-2.66454e-15,12)
                        Point(width;,0)
                        {
                            position(5.5,10)
                        }
                    }
                    Wall(wall_0003;,3)
                    {
                        transform(1,0,2,0,1,12)
                        Contour(contour;,0)
                        {
                            path(-2,6,-2,-6,4,-6,4,6)
                        }
                        Property(width;,1)
                        {
                            value(1;)
                        }
                    }
                }
                Connection(conn_0004;,4)
                {
                    transform(-2.66454e-15,1,16,-1,-2.66454e-15,-4)
                    Point(width;,0)
                    {
                        position(5.5,3)
                    }
                }
            }
            Connection(conn_0008;,8)
            {
                transform(-2.66454e-15,1,-82,-1,-2.66454e-15,4)
                Point(width;,0)
                {
                    position(19.5,5)
                }
            }
            Pin(pin__0009;,9)
            {
                position(-64,26)
                Property(lanes;,0)
                {
                    value(Pavement;)
                }
            }
        }
    }
}
