Schematic(base;,0)
{
    Property(laneRadius;,0)
    {
        value(0.75f;)
    }
    Property(laneLining;,1)
    {
        value(0.15f;)
    }
    Property(pavementRadius;,2)
    {
        value(2.25f;)
    }
    Property(pavementLining;,3)
    {
        value(0.15f;)
    }
    Property(clearance;,4)
    {
        value(3.5f;)
    }
    Space(spac_0005;,5)
    {
        transform(1,0,0,0,1,0)
        Contour(contour;,0)
        {
            path(0,0,128,0,128,128,0,128)
        }
        Property(width;,1)
        {
            value(0.25f;)
        }
        Space(space_0002;,2)
        {
            transform(1,0,76,0,1,48)
            Contour(contour;,0)
            {
                path(-32,32,-32,0,8,0,8,32)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(spac_0008;,2)
            {
                transform(-1,0,-5,0,1,0)
                Contour(contour;,0)
                {
                    path(0,0,16,0,16,16,0,16)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Property(lane_0004;,2)
                {
                    value(0.75f;)
                }
                Property(lane_0005;,3)
                {
                    value(0.15f;)
                }
                Property(pave_0006;,4)
                {
                    value(2.25f;)
                }
                Property(pave_0007;,5)
                {
                    value(0.15f;)
                }
                Property(clea_0008;,6)
                {
                    value(3.5f;)
                }
                Property(lane_0011;,7)
                {
                    value(0.75f;)
                }
                Property(lane_0012;,8)
                {
                    value(0.15f;)
                }
                Property(pave_0013;,9)
                {
                    value(2.25f;)
                }
                Property(pave_0014;,10)
                {
                    value(0.15f;)
                }
                Property(clea_0015;,11)
                {
                    value(3.5f;)
                }
                Property(lane_0016;,12)
                {
                    value(0.75f;)
                }
                Property(lane_0017;,13)
                {
                    value(0.15f;)
                }
                Property(pave_0018;,14)
                {
                    value(2.25f;)
                }
                Property(pave_0019;,15)
                {
                    value(0.15f;)
                }
                Property(clea_0020;,16)
                {
                    value(3.5f;)
                }
                Connection(conn_0017;,17)
                {
                    transform(-1,0,8,0,1,16)
                    Point(width;,0)
                    {
                        position(1.5,3)
                    }
                }
                Property(lane_0018;,18)
                {
                    value(0.75f;)
                }
                Property(lane_0019;,19)
                {
                    value(0.15f;)
                }
                Property(pave_0020;,20)
                {
                    value(2.25f;)
                }
                Property(pave_0021;,21)
                {
                    value(0.15f;)
                }
                Property(clea_0022;,22)
                {
                    value(3.5f;)
                }
            }
            Connection(conn_0010;,3)
            {
                transform(-1,-0,-13,0,1,-0)
                Point(width;,0)
                {
                    position(1.5,3)
                }
            }
        }
    }
    Property(lane_0006;,6)
    {
        value(0.75f;)
    }
    Property(lane_0007;,7)
    {
        value(0.15f;)
    }
    Property(pave_0008;,8)
    {
        value(2.25f;)
    }
    Property(pave_0009;,9)
    {
        value(0.15f;)
    }
    Property(clea_0010;,10)
    {
        value(3.5f;)
    }
}
