Schematic(base;,0)
{
    Space(space_0000;,0)
    {
        transform(1,0,0,0,1,0)
        Contour(contour;,0)
        {
            path(0,0,112,0,112,112,0,112)
        }
        Property(width;,1)
        {
            value(0.5f;)
        }
        Space(spac_0002;,2)
        {
            transform(1,0,32,0,1,84)
            Contour(contour;,0)
            {
                path(-16,-16,16,-16,16,16,-16,16)
            }
            Property(width;,1)
            {
                value(0.5f;)
            }
            Connection(conn_0002;,2)
            {
                transform(-2.66454e-15,1,-18,-1,-2.66454e-15,-5)
                Point(width;,0)
                {
                    position(5.5,6)
                }
            }
            Pin(pin__0003;,3)
            {
                position(8,9)
                Property(lanes;,0)
                {
                    value(Gutter;)
                }
            }
        }
        Space(spac_0003;,3)
        {
            transform(1,0,32,0,1,36)
            Contour(contour;,0)
            {
                path(-16,-16,16,-16,16,16,-16,16)
            }
            Property(width;,1)
            {
                value(0.5f;)
            }
            Connection(conn_0002;,2)
            {
                transform(-2.66454e-15,1,-16,-1,-2.66454e-15,0)
                Point(width;,0)
                {
                    position(7.5,3)
                }
            }
        }
        Space(spac_0004;,4)
        {
            transform(1,0,80,0,1,90)
            Contour(contour;,0)
            {
                path(-16,-16,24,-16,24,16,-16,16)
            }
            Property(width;,1)
            {
                value(0.5f;)
            }
            Connection(conn_0002;,2)
            {
                transform(-2.66454e-15,1,-16,-1,-2.66454e-15,2)
                Point(width;,0)
                {
                    position(7.5,3)
                }
            }
            Pin(pin__0003;,3)
            {
                position(-10,11)
                Property(lanes;,0)
                {
                    value(Pavement;)
                }
            }
            Space(space_0004;,4)
            {
                transform(1,0,6,0,1,-6)
                Contour(contour;,0)
                {
                    path(14,0,14,16,0,16,0,0)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,7,0,1,0)
                    Point(width;,0)
                    {
                        position(3.5,4)
                    }
                }
            }
        }
        Space(spac_0005;,5)
        {
            transform(1,0,82,0,1,36)
            Contour(contour;,0)
            {
                path(-16,-16,16,-16,16,16,-16,16)
            }
            Property(width;,1)
            {
                value(0.5f;)
            }
            Connection(conn_0002;,2)
            {
                transform(-2.66454e-15,1,-18,-1,-2.66454e-15,-5)
                Point(width;,0)
                {
                    position(5.5,6)
                }
            }
            Pin(pin__0003;,3)
            {
                position(-13,12)
                Property(lanes;,0)
                {
                    value(Gutter;)
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,-5,0,1,-2)
                Contour(contour;,0)
                {
                    path(13,0,13,9,2,9,2,0)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0002;,2)
                {
                    transform(1,0,8,0,1,0)
                    Point(width;,0)
                    {
                        position(2.5,2)
                    }
                }
            }
        }
    }
}
