Schematic(base;,0)
{
    Space(spac_0005;,0)
    {
        transform(1,0,0,0,1,0)
        Contour(contour;,0)
        {
            path(0,0,128,0,128,128,0,128)
        }
        Property(width;,1)
        {
            value(0.25f;)
        }
        Space(space_0002;,2)
        {
            transform(1,0,76,0,1,48)
            Contour(contour;,0)
            {
                path(-32,32,-32,0,8,0,8,32)
            }
            Property(width;,1)
            {
                value(0.25f;)
            }
            Space(spac_0008;,2)
            {
                transform(-1,0,-5,0,1,0)
                Contour(contour;,0)
                {
                    path(0,0,16,0,16,16,0,16)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Connection(conn_0017;,2)
                {
                    transform(-1,0,8,0,1,16)
                    Point(width;,0)
                    {
                        position(1.5,3)
                    }
                }
            }
            Connection(conn_0010;,3)
            {
                transform(-1,-0,-13,0,1,-0)
                Point(width;,0)
                {
                    position(1.5,3)
                }
            }
            Object(obje_0004;,4)
            {
                transform(1,0,-6.5,0,1,28)
                Contour(contour;,0)
                {
                    path(0,-4,4,-4,4,0,0,0)
                }
            }
            Wall(wall_0010;,5)
            {
                transform(1,0,4,0,1,8)
                Contour(contour;,0)
                {
                    path(2,0,0,-2,0,-8,4,-8,4,0)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Cut(cut_0002;,2)
                {
                    transform(1,0,3.75,0,1,-7.75)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(0,8)
                    }
                }
                Cut(cut_0003;,3)
                {
                    transform(1,0,-0.25,0,1,-7.75)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(4,0)
                    }
                }
                Pin(pin_0004;,4)
                {
                    position(1,-2)
                    Property(plane;,0)
                    {
                        value(Mid;)
                    }
                }
            }
            Wall(wall_0011;,6)
            {
                transform(-1,0,8,0,1,20.25)
                Contour(contour;,0)
                {
                    path(0,0,0,-8,4,-8,4,0)
                }
                Property(width;,1)
                {
                    value(0.25f;)
                }
                Cut(cut_0002;,2)
                {
                    transform(1,0,0.25,0,1,-8)
                    LineSegment(segment;,0)
                    {
                        start(0,-0.25)
                        end(0,8.25)
                    }
                }
                Pin(pin_0003;,3)
                {
                    position(3,-3.25)
                    Property(plane;,0)
                    {
                        value(Mid;)
                    }
                }
            }
        }
    }
}
