Schematic(base;,0)
{
    Space(space_0000;,0)
    {
        transform(1,0,0,0,1,0)
        Contour(contour;,0)
        {
            path(0,0,64,0,64,64,0,64)
        }
        Property(width;,1)
        {
            value(0.25;)
        }
        Space(space_0006;,2)
        {
            transform(1,-0,32,-0,1,34)
            Contour(contour;,0)
            {
                path(-16,-18,16,-18,16,18,-16,18)
            }
            Property(width;,1)
            {
                value(0.25;)
            }
            Space(spac_0002;,2)
            {
                transform(1,0,-16,0,1,2)
                Contour(contour;,0)
                {
                    path(0,0,12,0,12,8,16,12,16,16,0,16)
                }
                Property(width;,1)
                {
                    value(0.25;)
                }
                Object(obje_0002;,2)
                {
                    transform(1,0,19,0,1,26)
                    Contour(contour;,0)
                    {
                        path(-17,-16,-13,-16,-13,-12,-17,-12)
                    }
                }
            }
            Space(spac_0003;,3)
            {
                transform(1,0,-0,0,1,-18)
                Contour(contour;,0)
                {
                    path(0,0,16,0,16,16,0,16)
                }
                Property(width;,1)
                {
                    value(0.25;)
                }
                Cut(cut_0002;,2)
                {
                    transform(1,0,1,0,1,10)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(-2,0)
                    }
                }
                Cut(cut__0003;,3)
                {
                    transform(1,0,1,0,1,2)
                    LineSegment(segment;,0)
                    {
                        start(0,0)
                        end(-2,0)
                    }
                }
                Pin(pin_0004;,4)
                {
                    position(0,6)
                    Property(plane;,0)
                    {
                        value(Ground;)
                    }
                }
            }
            Space(spac_0004;,4)
            {
                transform(1,0,-0,0,1,2)
                Contour(contour;,0)
                {
                    path(-4,0,16,0,16,16,0,16,0,12,-4,8)
                }
                Property(width;,1)
                {
                    value(0.25;)
                }
                Cut(cut_0002;,2)
                {
                    transform(1,0,-2,0,1,-3)
                    LineSegment(segment;,0)
                    {
                        start(0,2)
                        end(0,4)
                    }
                }
                Cut(cut__0003;,3)
                {
                    transform(1,0,6,0,1,-3)
                    LineSegment(segment;,0)
                    {
                        start(0,2)
                        end(0,4)
                    }
                }
                Pin(pin_0004;,4)
                {
                    position(2,0)
                    Property(plane;,0)
                    {
                        value(Mid;)
                    }
                }
            }
            Space(spac_0005;,5)
            {
                transform(1,-0,-16,-0,1,-18)
                Contour(contour;,0)
                {
                    path(0,0,16,0,16,16,0,16)
                }
                Property(width;,1)
                {
                    value(0.25;)
                }
            }
            Connection(conn_0006;,6)
            {
                transform(-2.66454e-15,1,-16,-1,-2.66454e-15,0)
                Point(width;,0)
                {
                    position(1.5,1)
                }
            }
            Connection(conn_0007;,7)
            {
                transform(-2.66454e-15,1,16,-1,-2.66454e-15,0)
                Point(width;,0)
                {
                    position(1.5,1)
                }
            }
            Connection(conn_0008;,8)
            {
                transform(1,0,8,0,1,-2)
                Point(width;,0)
                {
                    position(1.5,1)
                }
            }
            Connection(conn_0009;,9)
            {
                transform(1,0,8,0,1,2)
                Point(width;,0)
                {
                    position(1.5,1)
                }
            }
            Connection(conn_0010;,10)
            {
                transform(1,0,-8,0,1,-2)
                Point(width;,0)
                {
                    position(1.5,1)
                }
            }
            Connection(conn_0011;,11)
            {
                transform(1,0,-8,0,1,2)
                Point(width;,0)
                {
                    position(1.5,1)
                }
            }
            Connection(conn_0012;,12)
            {
                transform(-2.66454e-15,1,0,-1,-2.66454e-15,-6)
                Point(width;,0)
                {
                    position(1.5,2)
                }
            }
            Connection(conn_0013;,13)
            {
                transform(-2.66454e-15,1,0,-1,-2.66454e-15,16)
                Point(width;,0)
                {
                    position(1.5,1)
                }
            }
        }
    }
}
